#pragma config(Sensor, S1,     ,               sensorEV3_Gyro, modeEV3Gyro_Rate)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 float y=0,a,x=0;
 motor[motorA] = 0;
 SensorValue[S1] = 0;
 while(true)
 {
   a = SensorValue[S1];
   motor[motorA] = -x;
   x = x+(a*0.019)+((y-a)*0.19);
   y = a;
  displayBigTextLine(1,"x%f",x);
}
}
