#pragma config(Sensor, S1,     ,               sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int x=0, a;
  motor[motorA] = 0;
  motor[motorB] = 0;
 while(x < 100)
 {
   a = SensorValue[S1];
   motor[motorA] = x + (a*0.6);
   motor[motorB] = x - (a*0.6);
   x=x+1;
   wait1Msec(100);
}
}
