#pragma config(Sensor, S1,     ,               sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 float y=0,a,x=0;
 motor[motorA] = 0;
 SensorValue[S1]=0;
 while(true)
 {
   a = SensorValue[S1];
   motor[motorA] = -x;
   x = (a*5)+((y-a)*0.2);
   y = a;
  displayBigTextLine(1,"x%f",x);
  displayBigTextLine(10,"x%f",a);
}
}
