#pragma config(Sensor, S1,     ,               sensorEV3_Gyro)
#pragma config(Sensor, S2,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     ,               sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
[sourcecode language="cpp"wraplines="false"collapse="false"]

task main()
{
	int message_first;
	int message_second;
	int message_third;
	while(true)
	{
		message_first=messageParm[0];
		message_second=messageParm[1];
		message_third=messageParm[2];
	if(message_first!=0||message_second!=0||message_third!=0)
	{
		DisplayBigtextLine(2,"1:%d",message_first);
		DisplayBigtextLine(4,"2:%d",message_second);
		DisplayBigtextLine(6,"3:%d",message_third);

	ClearMessage();
}
wait1Msec(500);
}
}
