#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S3,     ,               sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue[S3]==0)
	{
		motor[motorB]=0;
		motor[motorC]=0;
	}
	int i=0,a=0,b=0;
	while(true)
	{
		a=SensorValue[S1];
		i=i+(b-a);
		b=a;
		motor[motorB]=5-(0.5*i);
		motor[motorC]=5+(0.5*i);
	}
}
