#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 while(true)
 {
   int i = SensorValue[gyro];
   motor[motorB]=20-i;
   motor[motorC]=20+i;
 }

}
