#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int flag=0;
	while(true)
	{
		SensorValue[S2]=0;
		while(SensorValue[S2]==0)
		{
			if(SensorValue[S1]<15)
			{
				motor[motorB]=40;
				motor[motorC]=20;
				}else{
				motor[motorB]=20;
				motor[motorC]=40;
			}
		}
	if(flag == 0)
		{
			motor[motorB]=-50;
			motor[motorC]=-50;
			wait1Msec(2000);
			flag=1;
		}
		if(flag == 1)
		{
			motor[motorB]=0;
			motor[motorC]=0;
			wait1Msec(2000);
		}
	}
}
