#pragma config(Sensor, S1,     ,               sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
	{
		int i = SensorValue[S1];
		motor[motorB]=50;
		motor[motorC]=50;
		wait1Msec(2000);
		while(i<=180)
		{
		i=SensorValue[S1];
			motor[motorB]=10;
			motor[motorC]=-10;
		}
	motor[motorB]=50;
		motor[motorC]=50;
		wait1Msec(2000);
}
