#pragma config(Sensor, S1,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int a,b,c;
	a=SensorValue[S1];
  wait1Msec(500);
  motor[motorB] = 25;
  wait1Msec(1000);
  motor[motorB] = 0;
  b=SensorValue[S1];
  wait1Msec(500);
  c = (a+b)*0.5;
	while(true)
	{
		if(SensorValue[S1]>c)
		{
			motor[motorA] = 2*(SensorValue[S1]-c)+20;
			motor[motorB] = 20;
	}else{
	    motor[motorA] = 20;
	    motor[motorB] = 2*(c-SensorValue[S1])+20;
}
}
}
