#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 while(true)
 {
   int i = SensorValue[gyro];
   motor[motorB]=-(i-180);
   motor[motorC]=i-180;
 }


}
