#pragma config(Sensor, S1,     ,               sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int a=0,c=0;
	while (true)
	{
		a = SensorValue[S1];
		c=a*0.5;
		wait1Msec(10);
		motor[motorA] = 25+c;
		motor[motorD] = 25-c;
	}
}
