#pragma config(Sensor, S1,     at,             sensorEV3_Touch)
#pragma config(Sensor, S2,     bt,             sensorEV3_Touch)
#pragma config(Sensor, S3,     ct,             sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int ma = 0,mb = 0,mc  = 0;
int r = 1;
task a()
{
	int d;
	nMotorEncoder[motorA] = 0;
	while(r)
	{
		d = ma - nMotorEncoder[motorA];
	  //motor[motorA] = (15.0)*d;
		motor[motorA] = (15.0)*d;
	}
	motor[motorA] = 0;
	return;
}

task b()
{
	 int d;
	 nMotorEncoder[motorB] = 0;
	 while(r)
	 {
    d = mb - nMotorEncoder[motorB];
    motor[motorB] = (2.0)*d;
	 }
	  motor[motorB] = 0;
	 return;
}
task c()
{
	 int d;
	 nMotorEncoder[motorC] = 0;
	 while(r)
	 {
	 d = mc - nMotorEncoder[motorC];
	motor[motorC] = (2.0)*d;
	 }
	motor[motorC] = 0;
	 return;
}
task main()
{
	int bad;
	startTask(a);
	startTask(b);
	startTask(c);
	while(true)
	{
		if(SensorValue[at] == 0){
			bad = 1;
		}else{
		 bad = 0;
		}
		if(bad == 1 && SensorValue[bt] == 0 &&SensorValue[ct] == 0)
		{
			ma++;
			wait1Msec(10);
  	}
  	if(bad == 0 && SensorValue[bt] == 1 &&SensorValue[ct] == 1)
		{
			ma--;
			wait1Msec(10);
  	}
  	if(bad == 0 && SensorValue[bt] == 1 &&SensorValue[ct] == 0)
		{
			mb--;
			wait1Msec(10);
  	}
  	if(bad == 1 && SensorValue[bt] == 0 &&SensorValue[ct] == 1)
		{
			mb++;
			wait1Msec(10);
  	}
  	if(bad == 0 && SensorValue[bt] == 0 &&SensorValue[ct] == 1)
		{
			mc = -25;
  	}
  	if(bad == 1 && SensorValue[bt] == 1 &&SensorValue[ct] == 0)
		{
			mc = 20;
  	}
  	if(bad == 1 && SensorValue[bt] == 1 &&SensorValue[ct] == 1)
		{
			r = 0;
			wait1Msec(1000);
			return;
  	}
  	displayBigTextLine(1,"%d, %d ,%d ",ma,mb,mc);
  }
}
