#pragma config(Sensor, S1,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ,               sensorHTechicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		if(SensorValue[S2] == 5)
		{
			if(SensorValue[S1] < 7)
			{
				motor[motorA] = -50;
				motor[motorB] = -50;
				wait1Msec(200);
				motor[motorD] = 50;
				wait1Msec(100);

			} else {
			  motor[motorA] = -50;
			  motor[motorB] = -50;
			 wait1Msec(200);
		  }
		} else {
		 if(SensorValue[S2] >6)
		 {
		   motor[motorA] = -50;
		   motor[motorB] = 0;
		   wait1Msec(300);
		  } else {
		  if(SensorValue[S2] == 0)
		  {
		   motor[motorA] = -50;
		 	 motor[motorB] = -50;
			 wait1Msec(500);
		   } else {
		   motor[motorA] = 0;
		   motor[motorB] = -50;
		   wait1Msec(300);
		   }
		 }
    }
  }
}



