#pragma config(Sensor, S1,     t1,             sensorEV3_Touch, modeEV3Bump)
#pragma config(Sensor, S2,     t2,             sensorEV3_Touch, modeEV3Bump)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task  main()
{
	while (true)
	{
 if (SensorValue[t1] == 1 && SensorValue[t2] == 1)
{
	motor[motorA] = 50;
	motor[motorD] = 50;
}
else if (SensorValue[t1] == 1 && SensorValue[t2] == 0)
{
	motor[motorA] = 0;
	motor[motorD] = 50;
}
else if (SensorValue[t1] == 0 && SensorValue[t2] == 1)
{
	motor[motorA] = 50;
	motor[motorD] = 0;
}
else if (SensorValue[t1] == 0 && SensorValue[t2] == 0)
{
	motor[motorA] = 0;
	motor[motorD] = 0;
  }
 }
}
