#pragma config(Sensor, S1,     touch1,         sensorEV3_Touch)
#pragma config(Sensor, S2,     touch2,         sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 while (true)
 {
   if (SensorValue[touch1] == 1)
   {
     if (SensorValue[touch2] == 1)
     {
       motor[motorA] = 50;
       motor[motorD] = 50;
     } else {
     motor[motorA] = 0;
     motor[motorD] = 50;
     }
   } else {
     if (SensorValue[touch2] == 1)
     {
       motor[motorA] = 50;
       motor[motorD] = 0;
     } else {
       motor[motorA] = 0;
       motor[motorD] = 0;
   }
 }
}
}
