#pragma config(Sensor, S1,     IR,             sensorHTechicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 while(true)
 {
   int data;
   data=SensorValue[S1];
   displayBigTextLine(5,"%d",data);
   wait1Msec(1);
 }
}
