#pragma config(Sensor, S1,     ,               sensorEV3_Gyro, modeEV3Gyro_Rate)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	float a=0,b=0,c=0,d=0;
	motor[motorA] = 0;
	motor[motorD] = 0;
	wait1Msec(500);
	resetGyro(S1);

	while (true)
	{
		a = SensorValue[S1];
		d = (a-c)*10;
		b = SensorValue[S1]*0.1+b;
		wait1Msec(10);
		displayBigTextLine(1,"%d",a);
		motor[motorA] = (a*15.0)+(b*10.0)+(d*10.0); //(a*15.0)+(b*10.0)+(d*10.0); best 2/2
		motor[motorD] = (a*15.0)+(b*10.0)+(d*10.0);
		c=a;
	}
}
