#pragma config(Sensor, S1,     L1,             sensorLightActive)
#pragma config(Sensor, S2,     L2,             sensorEV3_Color)
#pragma config(Sensor, S3,     L3,             sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//color
#define WHITE 0
#define BLACK 1
#define SELBER 2
#define BLUEE  3
//action
//light
int Left_Light(void);
int Senter_Light(void);
int Rigth_Light(void);

//motor_
void Advance_motor(void);
void Rigth_motor(void);
void Left_motor(void);
void Back_motor(void);
void Stop_motor(void);
//motor_encoder
void E_A_motor(int n);
void E_R_motor(int n);
void E_L_motor(int n);
void E_B_motor(int n);
task main()
{
	int r,s,l;
	while(true)
{
		l=Left_Light();
		s=Senter_Light();
		r=Rigth_Light();

		if(s==WHITE && l==WHITE && r==BLACK){
			Back_motor();}
		if(s==WHITE && l==BLACK){
			Left_motor();}
		if(s==BLACK && l==WHITE){
			Rigth_motor();}
		if(s==WHITE && l==WHITE && r==WHITE){
			Stop_motor();}
	}
}
//
int Left_Light()
{
	int color,n;
	n = SensorValue(L1);
	if(n > 70)
	{
		displayBigTextLine(1,"L1=%d,silver",n);
		color = SELBER;
	}else if(n > 60)
	{
		displayBigTextLine(1,"L1=%d,white",n);
		color = WHITE;
	}else if(n >20)
	{
		displayBigTextLine(5,"L3=%d,silver",n);
    color = BLUEE;
	}else
	{
		displayBigTextLine(1,"L1=%d,black",n);
		color = BLACK;
	}
	return color;
}
int Senter_Light()
{
	int color,n;
	n = SensorValue(L2);
	if(n > 99)
	{
		displayBigTextLine(3,"L2=%d,silver",n);
		color = SELBER;
	}else if(n > 90)
	{
		displayBigTextLine(3,"L2=%d,white",n);
		color = WHITE;
  }else if(n > 70)
  {
  	displayBigTextLine(3,"L2=%d,white",n);
  	color = BLUEE;
	}else
	{
		displayBigTextLine(3,"L2=%d,black",n);
		color = BLACK;
	}
	return color;
}
int Rigth_Light()
{
	int color,n;
	n = SensorValue(L3);
	if(n > 63)
	{
		displayBigTextLine(5,"L3=%d,silver",n);
		color = SELBER;
	}else if(n > 56)
	{
		displayBigTextLine(5,"L3=%d,white",n);
		color = WHITE;
  }else if(n > 20)
  {
  	displayBigTextLine(5,"L3=%d,silver",n);
    color = BLUEE;
	}else
	{
		displayBigTextLine(5,"L3=%d ,black",n);
		color = BLACK;
	}
	return color;
}
void Advance_motor()
{
	motor[motorA] = 50;
	motor[motorD] = 50;
}
void Rigth_motor()
{
	motor[motorA] = -70;
	motor[motorD] = 0;
}
void Left_motor()
{
	motor[motorA] = 0;
	motor[motorD] = -70;
}
void Back_motor()
{
	motor[motorA] = -70;
	motor[motorD] = -70;
}
void Stop_motor()
{
	motor[motorA] = 0;
	motor[motorD] = 0;
}
void E_A_motor(int n)
{
	nMotorEncoder[motorA] = 0;
	nMotorEncoder[motorD] = 0;
	while((nMotorEncoder[motorA] < n)||(nMotorEncoder[motorD] < n))
	{
		motor[motorA] = 20;
		motor[motorD] = 20;
	}
}
void E_R_motor(int n)
{
	nMotorEncoder[motorA] = 0;
	nMotorEncoder[motorD] = 0;
	while((nMotorEncoder[motorA] < n)||(nMotorEncoder[motorD] > -n))
	{
		motor[motorA] = 20;
		motor[motorD] = -20;
	}
}
void E_L_motor(int n)
{
	nMotorEncoder[motorA] = 0;
	nMotorEncoder[motorD] = 0;
	while((nMotorEncoder[motorA] > -n)||(nMotorEncoder[motorD] < n))
	{
		motor[motorA] = -20;
		motor[motorD] = 20;
	}
}
void E_B_motor(int n)
{
	nMotorEncoder[motorA] = 0;
	nMotorEncoder[motorD] = 0;
	while((nMotorEncoder[motorA] > -n)||(nMotorEncoder[motorD] > -n))
	{
		motor[motorA] = -20;
		motor[motorD] = -20;
	}
}
