#pragma config(Sensor, S1,     R,              sensorLightActive)
#pragma config(Sensor, S2,     L,              sensorLightActive)
#pragma config(Sensor, S3,     S,              sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int BLACK = 0,WHITE = 1,SILBER = 2;
///////////////////////////////////////////////////////////////////////////////////////
void Motor_Go(int p);
void Motor_Left(int p);
void Motor_Right(int p);
void Motor_Stop(void);
void N_Motor_Go(int p,int n);
void N_Motor_Back(int p,int n);
void N_Motor_Left(int p,int n);
void N_Motor_Right(int p,int n);
int Ligth_Left(void);
int Ligth_Right(void);
int Ligth_Senter(void);
task main()
{
	int r,l,s;
	while(true){
		l = Ligth_Left();
		s = Ligth_Senter();
		r = Ligth_Right();
		if( ( !(r == BLACK) )  &&  ( !(l == BLACK) )  ){
			Motor_Go(20);
		}else if( (r == BLACK)  &&  ( !(l == BLACK) )  ){
			Motor_Right(20);
		}else if( ( !(r == BLACK) )  &&  (l == BLACK)  ){
			Motor_Left(20);
		}else if( (r == BLACK)  &&  (l == BLACK)  ){
			Motor_Go(20);
		}

		///////////////////////////////////////////////////////////
	}
}
void Motor_Go(int p)
{
	motor[motorA] = p;
	motor[motorB] = p;
}
void Motor_Left(int p)
{
	motor[motorA] = 0;
	motor[motorB] = p;
}
void Motor_Right(int p)
{
	motor[motorA] = p;
	motor[motorB] = 0;
}
void Motor_Stop()
{
	motor[motorA] = 0;
	motor[motorB] = 0;
}
void N_Motor_Go(int p,int n)
{
	nMotorEncoder[motorA] = 0;
	nMotorEncoder[motorB] = 0;
	motor[motorA] = p;
	motor[motorB] = p;
	while(nMotorEncoder[motorA] < n){}
	motor[motorA] = 0;
	motor[motorB] = 0;
}
void N_Motor_Back(int p,int n)
{
	nMotorEncoder[motorA] = 0;
	nMotorEncoder[motorB] = 0;
	motor[motorA] = -p;
	motor[motorB] = -p;
	while(nMotorEncoder[motorA] > -n){}
	motor[motorA] = 0;
	motor[motorB] = 0;
}
void N_Motor_Left(int p,int n)
{
	nMotorEncoder[motorA] = 0;
	nMotorEncoder[motorB] = 0;
	motor[motorA] = -p;
	motor[motorB] = p;
	while(nMotorEncoder[motorB] < n){}
	motor[motorA] = 0;
	motor[motorB] = 0;
}
void N_Motor_Right(int p,int n)
{
	nMotorEncoder[motorA] = 0;
	nMotorEncoder[motorB] = 0;
	motor[motorA] = p;
	motor[motorB] = -p;
	while(nMotorEncoder[motorA] < n){}
	motor[motorA] = 0;
	motor[motorB] = 0;
}
int Ligth_Left()
{
	int data,color;
	data = SensorValue[S1];
	if(data > 79){
		displayBigTextLine(1,"SILBER:%d",data);
		color = SILBER;
	}else if(data > 40){
		displayBigTextLine(1,"WHITE :%d",data);
		color = WHITE;
	}else{
		displayBigTextLine(1,"BLACK :%d",data);
		color = BLACK;
	}
	return color;
}
int Ligth_Right()
{
	int data,color;
	data = SensorValue[S3];
	if(data > 60){
		displayBigTextLine(3,"SILBER:%d",data);
		color = SILBER;
	}else if(data > 40){
		displayBigTextLine(3,"WHITE :%d",data);
		color = WHITE;
	}else{
		displayBigTextLine(3,"BLACK :%d",data);
		color = BLACK;
	}
	return color;
}
int Ligth_Senter()
{
	int data,color;
	data = SensorValue[S2];
	if(data > 60){
		displayBigTextLine(5,"SILBER:%d",data);
		color = SILBER;
	}else if(data > 45){
		displayBigTextLine(5,"WHITE :%d",data);
		color = WHITE;
	}else{
		displayBigTextLine(5,"BLACK :%d",data);
		color = BLACK;
	}
	return color;
}
