#pragma config(Sensor, S1,     color_white,    sensorEV3_Color)
#pragma config(Sensor, S2,     color_black,    sensorEV3_Color)
#pragma config(Sensor, S3,     color_gray,     sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void Motor_Left(int p);
void Motor_Right(int p);
void Motor_Go(int p);
int Sensor_White(void);
int Sensor_Gray(void);
int Sensor_Black(void);
task main()
{
  int b,w,g,bw,po;
  while(true){
  	b = Sensor_Black();
  	w = Sensor_White();
  	g = Sensor_Gray();
  	bw = 48;///(b+w)*0.5;
  	if(g>bw){
  		po=(g-bw)*0.6+40;
  		Motor_Left(po);
    }else if(g < bw){
      po=(bw-g)*0.6+40;
      Motor_Right(po);
   }else{
      Motor_Go(20);
    }
}
}

void Motor_Left(int p){
	motor[motorB]=0;
	motor[motorC]=-p;
}
void Motor_Right(int p){
	motor[motorB]=-p;
	motor[motorC]=0;
}
void Motor_Go(int p){
	motor[motorB]=-p;
	motor[motorC]=-p;
}
int Sensor_White(){
	int wh;
	wh = SensorValue[color_white];
	return wh;
}
int Sensor_Black(){
	int bl;
	bl = SensorValue[color_black];
	return bl;
}
int Sensor_Gray(){
	int gr;
	gr = SensorValue[color_gray];
	return gr;
}
