#pragma config(Sensor, S1,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ,               sensorEV3_IRSensor)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 motor[motorA]= -50;
 motor[motorB]= -50;
 wait1Msec(2500);
 motor[motorA]= -50;
 motor[motorB]= 0;
 wait1Msec(900);
 motor[motorA]= -50;
 motor[motorB]= -50;
 wait1Msec(1750);
 motor[motorA]= -50;
 motor[motorB]= 0;
 wait1Msec(900);
 motor[motorA]= -50;
 motor[motorB]= -50;
 wait1Msec(2000);
 motor[motorA]= 0;
 motor[motorB]= 50;
 wait1Msec(900);

}
