#pragma config(Sensor, S2,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     ,               sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue[S2]>30)
	{
		motor[motorB]=50;
		motor[motorC]=50;
	}
	while(SensorValue[S4]==0)
	{
		motor[motorB]=30;
		motor[motorC]=30;
	}
	while(SensorValue[S2]<50)
	{
		motor[motorB]=-50;
		motor[motorC]=-50;
	}
}
