#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  setSensorMode(gyro, modeEV3Gyro_Rate);
  float sum = 70;
  while (true)
  {
  	sum = sum + SensorValue[gyro] / 10;
  	motor[motorA] = (-2.0) * sum;
  	motor[motorD] = (-2.0) * sum;
  	wait1Msec(10);
  }
}
