#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     touch,          sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		if (SensorValue[touch] == 1 && SensorValue[touch] == 1)
		{
			motor[motorA] = 50;
			motor[motorD] = 50;
		}
		else if (SensorValue[touch] == 1 && SensorValue[touch] == 0)
		{
			motor[motorA] = 0;
			motor[motorD] = 50;
		}
		else if (SensorValue[touch] == 0 && SensorValue[touch] == 1)
		{
			motor[motorA] = 50;
			motor[motorD] = 0;
		}
		else if (SensorValue[touch] == 0 && SensorValue{touch] == 0)
			{
				motor[motorA] = 0;
				motor[motorD] = 0;
			}
		}
	}
