#pragma config(Sensor, S1,     ,               sensorEV3_Gyro)
#pragma config(Sensor, S2,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     ,               sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task A()
 {
  while(SensorValue[S1]<45)
   {
     motor[motorA] = -10;
     wait1Msec(100);
   }
 }


task main()
{
	int a,b,c
 while(true)
 {
   motor[motorA] = -10;
   wait1Msec(1000);
   resetGyro(S1);
   wait1Msec(1000);
   startTask(A);
   wait1Msec(1000);
   SensorValue[S2] = a;

}
}
