#pragma config(Sensor, S1,     ,               sensorEV3_Touch)
#pragma config(Sensor, S3,     S2,             sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int a;
while(true)
{
while(SensorValue(S1)==1)
{
 SensorValue(S2) = a;
 wait1Msec(500);
}
wait1Msec(1000);
motor[motorD]=-50;
}
}
