#pragma config(Sensor, S1,     ,               sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
 if(SensorValue[S1] == 1)
 {
   motor[motorA] = 150;
   motor[motorB] = 150;
   motor[motorC] = -200;
   wait1Msec(5000);
}
}
}
