#pragma config(Sensor, S1,     ,               sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void a(int p,int d);

task main()
{
motor[motorA] = 0;
motor[motorD] = 0;
wait1Msec(500);
resetGyro(S1);
wait1Msec(1000);
setSensorMode(S1,	modeEV3Gyro_RateandAngle);
wait1Msec(1000);
a(20,90);
wait1Msec(100);
}

void a(int p,int d)
{
	motor[motorA] = -p;
	motor[motorD] = p;
	while(SensorValue[S1] < d){
		displayBigTextLine(1,"%d",SensorValue[S1]);
	}
motor[motorA] = 0;
motor[motorD] = 0;
wait1Msec(500);
resetGyro(S1);
}
