#pragma config(Sensor, S1,     ,               sensorEV3_Touch)
#pragma config(Sensor, S2,     ,               sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 while(true)
 {
   int a = 0;
   if(SensorValue[S1] == 0)
   {
     a = 0.48*SensorValue[S2];

     switch(a)
     {
       case 1:
       playTone(261.63,0);
       break;

       case 2:
       playTone(293.67, 0);
       break;

       case 3:
       playTone(329.63, 0);
       break;

       case 4:
       playTone(349.23, 0);
       break;

       case 5:
       playTone(392.00, 0);
       break;

       case 6:
       playTone(440.00, 0);
       break;


       case 7:
       playTone(493.88, 0);
       break;

       case 8:
       playTone(523.25, 0);
       break;

       default:
       break;

}
}
}
}
